GET http://127.0.0.1:8000/products/  HTTP/1.1



####

POST http://127.0.0.1:8000/products/  HTTP/1.1
Content-Type: application/json

{
    "description": "New product 3",
    "name": "product3",
    "price": 153.00,
    "stock": 3
    
}